---
title: "Impact of U.S. Politics on New York Times Headlines"
author: "Karim Zakir"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---
<br>

## Introduction to the Project

Reading the news, whether in print or digital forms, has become a daily ritual for over 3 billion people. The wide variety of news outlets help us stay up-to-date with the current events and provide us with a significant outlook on today's issues and the world in general. To provide its readers with the most accurate outlook, the news should be reported as neutrally as possible, ensuring that no bias occurs in the reporting. It is especially important that the writer does not let their personal biases impact their writing or how they report on different topics, unless it is an opinion piece. As the news has grown to be a global practice, however, certain news outlets have become very closely aligned with particular political parties and have allowed these alignments dictate how they report the news and what kind of topics they report on. This allows them to target specific groups of people who align themselves with the same or similar political parties or have the same political views as the news outlet.

The two most famous examples of this are CNN and Fox News in the United States (U.S.). CNN is considered to strongly align with the U.S. Democratic Party, while Fox News aligns more closely aligns with the Republican Party. These political beliefs strongly influence how these news outlets report on different topics, which, naturally, attracts different kinds of audiences. It could be argued that this kind of approach to news-making has possibly created a political divide in the country, since the two audiences have different and skewed viewpoints of the country and the world in general.

A newspaper that could possibly align themselves politically is the New York Times (NYT). Based in New York, U.S., the newspaper is one of the biggest news outlets in the world. It is considered to be a trustworthy source and is read by a large population. However, does the New York Times and its writers let their political beliefs influence how they write their articles? For instance, if in a given year, the Democratic party holds the most power in the country, do the NYT writers report more negative or positive news?

To investigate this question, I will consider all of the news headlines written in the NYT between 2013 and 2020 inclusive. Since it is hard to decide which political party had the most power in any given year, I will use the political party of that year's president as a proxy for that metric. Between 2013 and 2016, Barack Obama, who is a member of the Democratic Party, was the president of the U.S., so those years would be considered as the years when the Democrats had the most power in the country. Between 2017 and 2020, Donald Trump, who is a member of the Republican Party, was the president of the U.S., so those years would be considered as the years when the Republicans held the most power.

Throughout this investigation, I will answer the research question "does the NYT change how they write their headlines based on the party of the current United States president"? In particular, do NYT writers include more negative words in their headlines when the president of the U.S. belongs to a Democratic or Republican party? Similarly, when does the news outlet use more positive words in its headlines? I chose to focus on the headlines of these articles, since those are the first pieces of the articles that the reader sees and is, most-likely, what the reader skims when reading the news, so the reader's first impressions of the article and the current affairs are based on these headlines.

The dataset I will be using to answer these questions contains the headlines of all of the NYT articles written between 2013 and 2020 (inclusive), as well as other information, like their publication date, section name, and abstract. 

## Access the Project

To view the full report, please [click here](https://github.com/karimzakir02/jsc370-final-project/blob/main/final_project_report.pdf)